
Mov_dia = """
SELECT * FROM VIX_PROD_ESTOQUE
"""


entradas_fiscais = """
WITH
TIPOS_ENTRADAS AS (
	SELECT 
		U.NOME,
		T.NUMEROTRANSACAO,
		T.DATAINCLUSAO,
		CASE 
			WHEN TP.TIPO IN ('AR', 'OC') THEN 'NF ARMACOES'
			WHEN TP.TIPO = 'LG' THEN 'NF LENTES'
		END TIPO
	FROM ENTRADA e 
	JOIN TRANSACAO t 
	ON t.COD_TRANSACAO  = e.COD_ENTRADA 
	JOIN PESSOA F
		ON F.COD_PESSOA  = t.COD_PESSOA  AND f.PESSOAFORNECEDOR = 'T'
	JOIN PESSOA l
		ON l.COD_PESSOA  = t.COD_EMPRESA 
	JOIN USUARIO u 
		ON U.COD_USUARIO = T.COD_USUARIO
	LEFT JOIN TRANSACAO_ITEM ti 
		ON TI.COD_TRANSACAO = T.COD_TRANSACAO 
	LEFT JOIN TABELA_PRODUTO tp 
		ON TP.COD_PRODUTO  = TI.COD_ITEM 	
	WHERE 
	T.DATAINCLUSAO >= '{datainit}'
	AND U.COD_GRUPOUSUARIO = 3
	AND T.TIPOTRANSACAO = 'ENF'
	AND TP.TIPO IN ('AR', 'OC', 'LG')
	GROUP BY 
		U.NOME,
		T.NUMEROTRANSACAO,
		T.DATAINCLUSAO,
		CASE 
			WHEN TP.TIPO IN ('AR', 'OC') THEN 'NF ARMACOES'
			WHEN TP.TIPO = 'LG' THEN 'NF LENTES'
		END
)
SELECT 
    TE.NOME,
    TE.DATAINCLUSAO,
    TE.TIPO,
    COUNT(TE.NUMEROTRANSACAO) QUANTIDADE
FROM TIPOS_ENTRADAS TE
GROUP BY 
    TE.NOME,
    TE.DATAINCLUSAO,
    TE.TIPO

"""